name: invoice_duldul
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - tqdm
  - pip:
      - albucore==0.0.12
      - albumentations==1.4.10
      - annotated-types==0.7.0
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.1.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - filelock==3.15.4
      - fonttools==4.53.0
      - fsspec==2024.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - idna==3.7
      - imageio==2.34.2
      - importlib-resources==6.4.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - networkx==3.1
      - opencv-python-headless==4.10.0.84
      - packaging==24.1
      - pillow==10.3.0
      - pip==24.0
      - platformdirs==4.2.2
      - protobuf==5.27.2
      - psutil==6.0.0
      - py-cpuinfo==9.0.0
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - pyparsing==3.1.2
      - pytesseract==0.3.10
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - requests==2.32.3
      - scikit-image==0.21.0
      - sentry-sdk==2.6.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sympy==1.12.1
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - tomli==2.0.1
      - torch==2.3.1
      - torchvision==0.18.1
      - tqdm==4.66.4
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - zipp==3.19.2
